disabled_rules:
  - closure_parameter_position
  - weak_delegate
  - identifier_name
  - force_cast
  - file_length
  - type_body_length

opt_in_rules:
  - indentation_width 


indentation_width:
  severity: .warning,
  indentationWidth: 4,
  includeComments: true