version: 2.1

jobs:

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: make lint
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

workflows:
  patchday-checks:
    jobs:
      - swiftlint
