version: 2.1

jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: make lint
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  
  build-and-test:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: make test
      - store_artifacts:
          path: test_result.xml
      - store_test_results:
          path: test_result.xml

workflows:
  patchday-checks:
    jobs:
      - swiftlint
      - build-and-test
